version: "2"
services:
  elasticsearch:
    image: "docker.io/bitnami/elasticsearch:7.10.2"
    volumes:
      - "elasticsearch_data:/bitnami/elasticsearch"
  kibana:
    image: "docker.io/bitnami/kibana:7.10.2-debian-10"
    ports:
      - "5601:5601"
    volumes:
      - "kibana_data:/bitnami/kibana"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
